version: '3.1'

services:
  db:
    container_name: ajosavingspostgres-container
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gabson12@
      POSTGRES_DB: AjoSavings
    ports:
      - "5438:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres-dataz:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: .
    container_name: ajosavings-container2
    restart: always
    ports:
      - "8086:8084"
    expose:
      - "8084"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/AjoSavings
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Gabson12@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    image: ajo-savings-backend2

